// <auto-generated />
using System;
using LanguageCourses.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguageCourses.API.Migrations
{
    [DbContext(typeof(LanguageCoursesDbContext))]
    [Migration("20231208203210_First migration")]
    partial class Firstmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanguageCourses.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("cfeb0e5e-5d09-464a-82dd-fe5d39e45ad9"),
                            Email = "filipj@gmail.com",
                            FirstName = "Filip",
                            LastName = "Jovanovic",
                            Password = "password1",
                            Phone = "062 3856 142",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("af19ba81-1376-4a55-b2f3-a0cb6782f491"),
                            Email = "lukap@gmail.com",
                            FirstName = "Luka",
                            LastName = "Petrovic",
                            Password = "password2",
                            Phone = "065 9934 376",
                            Role = 2
                        },
                        new
                        {
                            Id = new Guid("998902da-c58d-4963-ae0d-39079971e5cd"),
                            Email = "bojanaa@gmail.com",
                            FirstName = "Bojana",
                            LastName = "Aleksijevic",
                            Password = "password3",
                            Phone = "060 9603 672",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("b0f6f6f3-9077-4186-a22e-8f9df4198d71"),
                            Email = "andrijanam@gmail.com",
                            FirstName = "Andrijana",
                            LastName = "Mihailovic",
                            Password = "password4",
                            Phone = "060 9603 672",
                            Role = 1
                        },
                        new
                        {
                            Id = new Guid("c8d54e95-6d30-4667-b07e-cd30c4160d59"),
                            Email = "aleksandardj@gmail.com",
                            FirstName = "Aleksandar",
                            LastName = "Djordjevic",
                            Password = "password5",
                            Phone = "060 4622 672",
                            Role = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
