// <auto-generated />
using System;
using LanguageCourses.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LanguageCourses.API.Migrations
{
    [DbContext(typeof(LanguageCoursesDbContext))]
    partial class LanguageCoursesDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.14")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LanguageCourses.API.Models.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Duration")
                        .HasColumnType("int");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Level")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Price")
                        .HasColumnType("int");

                    b.Property<Guid>("ProfessorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("7fca3cd1-6d04-4ac1-bff6-57cb3a23e34a"),
                            Available = true,
                            Description = "Description for Course 1",
                            Duration = 0,
                            Language = "Engleski",
                            Level = "B1",
                            Name = "Course 1",
                            Price = 0,
                            ProfessorId = new Guid("9150584f-eb77-4a84-a13f-698a581985d8"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("053504c1-bfad-4ec1-9932-1e7b5e536ce8"),
                            Available = true,
                            Description = "Description for Course 2",
                            Duration = 0,
                            Language = "Engleski",
                            Level = "C1",
                            Name = "Course 2",
                            Price = 0,
                            ProfessorId = new Guid("9150584f-eb77-4a84-a13f-698a581985d8"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("d1b4704a-5a5a-4b51-ab72-68b5db496d96"),
                            Available = true,
                            Description = "Description for Course 3",
                            Duration = 0,
                            Language = "Engleski",
                            Level = "B2",
                            Name = "Course 3",
                            Price = 0,
                            ProfessorId = new Guid("4f96f59a-a880-4f17-955a-c7d94f36f6ed"),
                            Type = 0
                        },
                        new
                        {
                            Id = new Guid("c8b98b9e-a370-4c71-b899-ad558f4124b8"),
                            Available = true,
                            Description = "Description for Course 4",
                            Duration = 0,
                            Language = "Engleski",
                            Level = "C2",
                            Name = "Course 4",
                            Price = 0,
                            ProfessorId = new Guid("4f96f59a-a880-4f17-955a-c7d94f36f6ed"),
                            Type = 0
                        });
                });

            modelBuilder.Entity("LanguageCourses.API.Models.CourseUser", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EnrollmentDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.HasKey("UserId", "CourseId");

                    b.HasIndex("CourseId");

                    b.ToTable("Enrollments");
                });

            modelBuilder.Entity("LanguageCourses.API.Models.Lesson", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("Lessons", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("961fa56e-71a8-4186-8a8d-488143d6a260"),
                            Content = "Content 1",
                            CourseId = new Guid("7fca3cd1-6d04-4ac1-bff6-57cb3a23e34a"),
                            Title = "Title 1"
                        },
                        new
                        {
                            Id = new Guid("e0c98ea1-2644-4ff0-8f2e-e7d30a3f2a6b"),
                            Content = "Content 2",
                            CourseId = new Guid("7fca3cd1-6d04-4ac1-bff6-57cb3a23e34a"),
                            Title = "Title 2"
                        },
                        new
                        {
                            Id = new Guid("b2d89a70-2ac5-4d26-94b9-ef99b746a388"),
                            Content = "Content 3",
                            CourseId = new Guid("053504c1-bfad-4ec1-9932-1e7b5e536ce8"),
                            Title = "Title 3"
                        },
                        new
                        {
                            Id = new Guid("ed0632a3-1b00-421c-be7f-044253c2d820"),
                            Content = "Content 4",
                            CourseId = new Guid("053504c1-bfad-4ec1-9932-1e7b5e536ce8"),
                            Title = "Title 4"
                        },
                        new
                        {
                            Id = new Guid("e19c5e3e-c5aa-411d-b540-0597307daf79"),
                            Content = "Content 5",
                            CourseId = new Guid("d1b4704a-5a5a-4b51-ab72-68b5db496d96"),
                            Title = "Title 5"
                        },
                        new
                        {
                            Id = new Guid("1695a6e9-f4a8-45f2-8cc9-5ff0c01dad26"),
                            Content = "Content 6",
                            CourseId = new Guid("d1b4704a-5a5a-4b51-ab72-68b5db496d96"),
                            Title = "Title 6"
                        },
                        new
                        {
                            Id = new Guid("75f0edab-103a-46ac-aff0-1f17aca2d279"),
                            Content = "Content 7",
                            CourseId = new Guid("c8b98b9e-a370-4c71-b899-ad558f4124b8"),
                            Title = "Title 7"
                        },
                        new
                        {
                            Id = new Guid("c1c2c043-1385-47d0-9ec8-c8a6085bf0bc"),
                            Content = "Content 8",
                            CourseId = new Guid("c8b98b9e-a370-4c71-b899-ad558f4124b8"),
                            Title = "Title 8"
                        });
                });

            modelBuilder.Entity("LanguageCourses.API.Models.Review", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CourseId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("PostDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("CourseId1");

                    b.HasIndex("UserId");

                    b.ToTable("Posts", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("a4b12efb-c878-4a43-9197-1efdf1d33e4a"),
                            Content = "Content 1",
                            CourseId = new Guid("7fca3cd1-6d04-4ac1-bff6-57cb3a23e34a"),
                            PostDate = new DateTime(2024, 2, 3, 1, 11, 49, 503, DateTimeKind.Local).AddTicks(9484),
                            Rating = 5,
                            UserId = new Guid("9150584f-eb77-4a84-a13f-698a581985d8")
                        },
                        new
                        {
                            Id = new Guid("4abf8e23-8fbd-46a6-80dc-fedd31814e24"),
                            Content = "Content 2",
                            CourseId = new Guid("053504c1-bfad-4ec1-9932-1e7b5e536ce8"),
                            PostDate = new DateTime(2024, 2, 3, 1, 11, 49, 503, DateTimeKind.Local).AddTicks(9505),
                            Rating = 5,
                            UserId = new Guid("4f96f59a-a880-4f17-955a-c7d94f36f6ed")
                        },
                        new
                        {
                            Id = new Guid("5e6fdd45-3ba6-4019-af72-665d2e1a39aa"),
                            Content = "Content 3",
                            CourseId = new Guid("d1b4704a-5a5a-4b51-ab72-68b5db496d96"),
                            PostDate = new DateTime(2024, 2, 3, 1, 11, 49, 503, DateTimeKind.Local).AddTicks(9510),
                            Rating = 5,
                            UserId = new Guid("9150584f-eb77-4a84-a13f-698a581985d8")
                        },
                        new
                        {
                            Id = new Guid("87c1eb43-6bc9-4f0d-ab08-bf54a708c88c"),
                            Content = "Content 4",
                            CourseId = new Guid("c8b98b9e-a370-4c71-b899-ad558f4124b8"),
                            PostDate = new DateTime(2024, 2, 3, 1, 11, 49, 503, DateTimeKind.Local).AddTicks(9514),
                            Rating = 5,
                            UserId = new Guid("4f96f59a-a880-4f17-955a-c7d94f36f6ed")
                        },
                        new
                        {
                            Id = new Guid("5f632e40-9f96-4c75-9afa-59dc6460d8e0"),
                            Content = "Content 5",
                            CourseId = new Guid("7fca3cd1-6d04-4ac1-bff6-57cb3a23e34a"),
                            PostDate = new DateTime(2024, 2, 3, 1, 11, 49, 503, DateTimeKind.Local).AddTicks(9518),
                            Rating = 5,
                            UserId = new Guid("9150584f-eb77-4a84-a13f-698a581985d8")
                        },
                        new
                        {
                            Id = new Guid("d2d5b555-e8af-478b-a144-0ea40f7d4ed6"),
                            Content = "Content 6",
                            CourseId = new Guid("053504c1-bfad-4ec1-9932-1e7b5e536ce8"),
                            PostDate = new DateTime(2024, 2, 3, 1, 11, 49, 503, DateTimeKind.Local).AddTicks(9522),
                            Rating = 5,
                            UserId = new Guid("4f96f59a-a880-4f17-955a-c7d94f36f6ed")
                        },
                        new
                        {
                            Id = new Guid("4bc9fece-54dc-4cca-a31b-de8a0557f8da"),
                            Content = "Content 7",
                            CourseId = new Guid("d1b4704a-5a5a-4b51-ab72-68b5db496d96"),
                            PostDate = new DateTime(2024, 2, 3, 1, 11, 49, 503, DateTimeKind.Local).AddTicks(9526),
                            Rating = 5,
                            UserId = new Guid("9150584f-eb77-4a84-a13f-698a581985d8")
                        },
                        new
                        {
                            Id = new Guid("e8a67c2e-3943-44ed-9d6c-7a56565302e9"),
                            Content = "Content 8",
                            CourseId = new Guid("c8b98b9e-a370-4c71-b899-ad558f4124b8"),
                            PostDate = new DateTime(2024, 2, 3, 1, 11, 49, 503, DateTimeKind.Local).AddTicks(9529),
                            Rating = 5,
                            UserId = new Guid("4f96f59a-a880-4f17-955a-c7d94f36f6ed")
                        });
                });

            modelBuilder.Entity("LanguageCourses.API.Models.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("PasswordResetToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Picture")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ResetTokenExpires")
                        .HasColumnType("datetime2");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.Property<string>("VerificationToken")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("VerifiedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Users", (string)null);

                    b.HasData(
                        new
                        {
                            Id = new Guid("9150584f-eb77-4a84-a13f-698a581985d8"),
                            Email = "fjovanovic284@gmail.com",
                            FirstName = "Filip",
                            LastName = "Jovanović",
                            PasswordHash = new byte[] { 230, 205, 59, 211, 68, 111, 2, 11, 247, 237, 77, 153, 171, 5, 80, 159, 221, 233, 14, 62, 72, 66, 227, 94, 15, 61, 235, 237, 123, 86, 245, 118, 49, 147, 185, 17, 92, 33, 252, 56, 112, 173, 114, 136, 47, 12, 157, 190, 77, 235, 171, 132, 58, 171, 82, 250, 13, 143, 159, 24, 122, 106, 215, 172 },
                            PasswordSalt = new byte[] { 130, 92, 55, 210, 255, 154, 254, 79, 15, 157, 91, 76, 58, 69, 118, 136, 234, 31, 247, 3, 131, 12, 248, 100, 142, 73, 25, 47, 211, 181, 231, 146, 61, 201, 232, 27, 15, 196, 236, 40, 141, 52, 56, 226, 224, 178, 195, 254, 5, 241, 2, 103, 101, 200, 222, 128, 1, 252, 238, 43, 35, 118, 249, 196, 140, 228, 58, 213, 6, 149, 109, 249, 151, 178, 167, 174, 24, 172, 78, 31, 253, 167, 15, 53, 16, 254, 95, 208, 251, 181, 247, 238, 73, 255, 14, 92, 120, 247, 82, 140, 77, 238, 211, 48, 91, 27, 228, 63, 130, 119, 229, 197, 112, 181, 163, 222, 4, 217, 47, 107, 88, 71, 99, 120, 196, 61, 121, 109 },
                            Phone = "061 755 8995",
                            Picture = "9150584F-EB77-4A84-A13F-698A581985D8.jpg",
                            Role = 2,
                            VerificationToken = "755BDAE9C6DD3067A77BCF4427AC48F652F5E3FDE85B72E9A93B77C85590A98E5DF7B8835C72CD4A8AC57FE4398FA8D507B8D2FEC82FF1AA0D21DAF8F2E64DEB",
                            VerifiedAt = new DateTime(2024, 2, 3, 1, 11, 49, 502, DateTimeKind.Local).AddTicks(9151)
                        },
                        new
                        {
                            Id = new Guid("4f96f59a-a880-4f17-955a-c7d94f36f6ed"),
                            Email = "lule19@gmail.com",
                            FirstName = "Luka",
                            LastName = "Petrović",
                            PasswordHash = new byte[] { 230, 205, 59, 211, 68, 111, 2, 11, 247, 237, 77, 153, 171, 5, 80, 159, 221, 233, 14, 62, 72, 66, 227, 94, 15, 61, 235, 237, 123, 86, 245, 118, 49, 147, 185, 17, 92, 33, 252, 56, 112, 173, 114, 136, 47, 12, 157, 190, 77, 235, 171, 132, 58, 171, 82, 250, 13, 143, 159, 24, 122, 106, 215, 172 },
                            PasswordSalt = new byte[] { 130, 92, 55, 210, 255, 154, 254, 79, 15, 157, 91, 76, 58, 69, 118, 136, 234, 31, 247, 3, 131, 12, 248, 100, 142, 73, 25, 47, 211, 181, 231, 146, 61, 201, 232, 27, 15, 196, 236, 40, 141, 52, 56, 226, 224, 178, 195, 254, 5, 241, 2, 103, 101, 200, 222, 128, 1, 252, 238, 43, 35, 118, 249, 196, 140, 228, 58, 213, 6, 149, 109, 249, 151, 178, 167, 174, 24, 172, 78, 31, 253, 167, 15, 53, 16, 254, 95, 208, 251, 181, 247, 238, 73, 255, 14, 92, 120, 247, 82, 140, 77, 238, 211, 48, 91, 27, 228, 63, 130, 119, 229, 197, 112, 181, 163, 222, 4, 217, 47, 107, 88, 71, 99, 120, 196, 61, 121, 109 },
                            Phone = "064 765 9876",
                            Role = 2,
                            VerificationToken = "CA07D80E57A78F16E98C762D3B30724F7643C1879DCB5436C83D608C0E7B483F59FB1B784F42FA553951A83D4A0785E1CC47E9B82F2F4A369B9FBFF8BCD394E5",
                            VerifiedAt = new DateTime(2024, 2, 3, 1, 11, 49, 502, DateTimeKind.Local).AddTicks(9247)
                        },
                        new
                        {
                            Id = new Guid("73fb19cd-7b56-459e-8b84-be0d05dd67b6"),
                            Email = "boka0404002.ba@gmail.com",
                            FirstName = "Bojana",
                            LastName = "Aleksijević",
                            PasswordHash = new byte[] { 230, 205, 59, 211, 68, 111, 2, 11, 247, 237, 77, 153, 171, 5, 80, 159, 221, 233, 14, 62, 72, 66, 227, 94, 15, 61, 235, 237, 123, 86, 245, 118, 49, 147, 185, 17, 92, 33, 252, 56, 112, 173, 114, 136, 47, 12, 157, 190, 77, 235, 171, 132, 58, 171, 82, 250, 13, 143, 159, 24, 122, 106, 215, 172 },
                            PasswordSalt = new byte[] { 130, 92, 55, 210, 255, 154, 254, 79, 15, 157, 91, 76, 58, 69, 118, 136, 234, 31, 247, 3, 131, 12, 248, 100, 142, 73, 25, 47, 211, 181, 231, 146, 61, 201, 232, 27, 15, 196, 236, 40, 141, 52, 56, 226, 224, 178, 195, 254, 5, 241, 2, 103, 101, 200, 222, 128, 1, 252, 238, 43, 35, 118, 249, 196, 140, 228, 58, 213, 6, 149, 109, 249, 151, 178, 167, 174, 24, 172, 78, 31, 253, 167, 15, 53, 16, 254, 95, 208, 251, 181, 247, 238, 73, 255, 14, 92, 120, 247, 82, 140, 77, 238, 211, 48, 91, 27, 228, 63, 130, 119, 229, 197, 112, 181, 163, 222, 4, 217, 47, 107, 88, 71, 99, 120, 196, 61, 121, 109 },
                            Phone = "064 784 5668",
                            Role = 2,
                            VerificationToken = "37DF675988AE4A6797867FF05C8CF695C3D976FFDA941E3308725F89B7ACC5CAD202EB7B84FC68A29E7DACB2E50FA13FC6892CD440D24C7E4BF2324416B5E410",
                            VerifiedAt = new DateTime(2024, 2, 3, 1, 11, 49, 502, DateTimeKind.Local).AddTicks(9278)
                        });
                });

            modelBuilder.Entity("LanguageCourses.API.Models.CourseUser", b =>
                {
                    b.HasOne("LanguageCourses.API.Models.Course", "Course")
                        .WithMany("CourseUsers")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageCourses.API.Models.User", "User")
                        .WithMany("CourseUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageCourses.API.Models.Lesson", b =>
                {
                    b.HasOne("LanguageCourses.API.Models.Course", "Course")
                        .WithMany("Lessons")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");
                });

            modelBuilder.Entity("LanguageCourses.API.Models.Review", b =>
                {
                    b.HasOne("LanguageCourses.API.Models.Course", "Course")
                        .WithMany()
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LanguageCourses.API.Models.Course", null)
                        .WithMany("Reviews")
                        .HasForeignKey("CourseId1");

                    b.HasOne("LanguageCourses.API.Models.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("User");
                });

            modelBuilder.Entity("LanguageCourses.API.Models.Course", b =>
                {
                    b.Navigation("CourseUsers");

                    b.Navigation("Lessons");

                    b.Navigation("Reviews");
                });

            modelBuilder.Entity("LanguageCourses.API.Models.User", b =>
                {
                    b.Navigation("CourseUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
